services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_DOMAIN_NAME}_nginx
    hostname: web
    depends_on:
      - api
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - appnet

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ${APP_DOMAIN_NAME}_api
    hostname: api
    environment:
      NODE_ENV: development
      PORT: "3000"

      # Prisma/Postgres
      DATABASE_URL: "postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-app}@postgres:5432/${POSTGRES_DB:-app}?schema=public"

      # BullMQ/Redis
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      # optional if you use a single URL in code:
      REDIS_URL: "redis://redis:6379"
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      # Hot reload (dev). Remove in production.
      - ./api:/usr/src/app
    networks:
      - appnet
    expose:
      - "3000"

  postgres:
    build:
      context: ./postgresql
    image: app-postgres
    container_name: ${APP_DOMAIN_NAME}_postgres
    hostname: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgroot:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks: [appnet]

  redis:
    image: redis:7-alpine
    container_name: ${APP_DOMAIN_NAME}_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - appnet
  pgadmin:
    image: "dpage/pgadmin4"
    restart: always
    container_name: ${APP_DOMAIN_NAME}_pgadmin
    volumes:
      - pgadmin-storage:/var/lib/pgadmin
    networks: [appnet]
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
networks:
  appnet:

volumes:
  pgroot:
  pgadmin-storage:
  redisdata:
